import Head from 'next/head'

import Header from '@/components/Header'
import Packages from '@/components/Packages'
import Services from '@/components/Services'
import Form from '@/components/Form'
import About from '@/components/About'
import Locations from '@/components/Locations'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Packages />
        <Services />
        <Form />
        <About />
        <Locations />
      </main>
    </>
  )
}
